imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

  # calculates the allocations per request by using results from application and load
defaultScript:
  - |
    var allocations = benchmarks.jobs.application.results["runtime-counter/alloc-rate"]
    var rps = benchmarks.jobs.load.results["http/requests"];
    benchmarks.jobs.application.results["runtime-counter/alloc-per-request"] = allocations / rps;  

results: # creates results from measurements
- name: runtime-counter/alloc-rate/avg
  measurement: runtime-counter/alloc-rate
  description: Avg Allocation Rate (B/sec)
  format: n0
  aggregate: avg
  reduce: sum
  description: 90th Allocation Rate (B/sec)
  format: n0
  aggregate: percentile90
  reduce: sum
- name: runtime-counter/allow-per-request
  measurement: alloc-per-request
  description: Avg Allocations (/request)
  format: n0
  aggregate: max
  reduce: max

jobs:
  server:
    source:
      repository: https://github.com/Azure/azure-functions-host
      branchOrCommit: dev
      project: src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj
    readyStateText: Application started.
    arguments: "--urls http://*:5000"

    environmentVariables:
      AzureWebJobsSecretStorageType: Files
      AzureWebJobsScriptRoot: ../../../sample/CSharpBenchmark
    options:
      collectCounters: true
      displayBuild: true
      displayOutput: true
    buildArguments: 
      - "/p:PublishReadyToRun=false"

scenarios:
  functions-baseline:
    application:
      job: server
      source:
        branchOrCommit: dev

    load:
      job: bombardier
      variables:
        #https: true
        serverPort: 5000
        path: "/api/HttpTriggerAnon?name=bob"
